#!/bin/bash


if [ "$1" = "static" ]; then
  rsync --verbose --recursive --chmod=ug=rwX,o=rX --delete "/home/alex/Documents/Blog files/" 192.168.13.14:static
elif [ "$1" = "staging" ]; then
  hugo \
    --buildDrafts \
    --buildFuture \
    --baseURL "https://staging.alexandre.deverteuil.net/" \
  && rsync --verbose --recursive --chmod=ug=rwX,o=rX --delete public/ 192.168.13.14:staging
else
  hugo \
  && rsync --verbose --recursive --chmod=ug=rwX,o=rX --delete public/ 192.168.13.14:public
fi
